### ISSUE TITLE
无法编译通过

### ISSUE THREAD

**Issue by shs1989** [artillerymans/androidSystemUI#1]
错误: 找不到符号
符号:   类 R
位置: 程序包 com.android.settingslib

我也调整了app.iml的 <orderEntry type="jdk" jdkName="Android API 25 Platform" jdkType="Android SDK" />的顺序后，扔不可以。
可以提供一些 能顺利编译出7.1 SystemUI apk排查方法给我吗？非常感谢.

**Comment by artillerymans** [comment]
我调整顺序进行clear然后进行编译 一些飘红的不用管 这个R包我记得我是出来过的资源文件 不用管删掉 然后把报错的java类文件关闭继续编译 很顺利的通过啦

**Comment by artillerymans** [comment]
对了  这个项目你要主要根目录下面的build.gradle文件 其中引用了系统jar包，那个路径你需要改一下，我这个工程是在Linux环境（Deepin）下，如果你的是Windows环境，这个估计你要自己调整一下
